#!/bin/bash


wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/SUGARA.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/SUGAR.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/finteh_plane.png
wget https://raw.githubusercontent.com/BlockABC/eos-tokens/master/tokens/pumlhealthio/PUML.png
wget https://www.api.bloks.io/image-proxy/display?w=100&h=100&url=https://statics.tokenpocket.pro/avatar/1593787035-amzcoinvault.png&op=resize
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/core.ogx-ODOT.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/core.ogx-OEOS.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/core.ogx-OETH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/core.ogx-OUSD.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/core.ogx-OTRX.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/OTU.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/STE.png
wget https://www.api.bloks.io/image-proxy/display?w=70&h=70&url=https://ndi.340wan.com/eos/eosreeltoken-er.png&op=resize
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/consortium.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/metpacktoken-mpt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/8x8_symbol.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/VIG.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/VIGOR.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/upd-symbol-icon.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ADE-logo-225x225.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosnow.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/anx-sm.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/appicsappics-apx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/atidium.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/atmos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/BBC.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bean.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/token.defi-box.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bg.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosbet.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/betking.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosblack.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bless.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bancor.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bnteos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bntusdt.jpeg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ethbnt.jpeg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/boidlogo.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/carmel.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/chaince.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/chintai-chex.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/CHLnewPNG500.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/carbonlogo-64.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dabble.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dapp.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dai.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/deosgames.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/defi.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/downcoinlogo.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dice.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dig.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dragon.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/DS.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ecoin.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eap.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bitpietokens-ebtc.png
wget https://raw.githubusercontent.com/BlockABC/eos-tokens/master/tokens/horustokenio/ECASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/efx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/emanate-mnx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/emanate.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosdac.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosn.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eoxcommerce.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ero.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ero.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/europechain.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/fair.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/fast.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/horuspay.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/HFC.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/hvt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/hub.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/infiniverse.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/everipedia.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosjacks.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/karma-wax.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/karma.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/KROWN.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/led.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/licc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lkg.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lelego.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lumeos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/worktokenbviLYNX.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dmail.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/meetone.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/rexnet.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/mev.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/mortys.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/nfx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ndx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/oraclechain.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pay.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/peos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/holon.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pixeos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/PIZZA.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/poker.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/poorman.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/gpk.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/gpk.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pgl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pgl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pool.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken.sx-sxa.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/crt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/cryptopeso.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pub.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pixels.jpeg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ramtoken.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/rcx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ridl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/rocketbattle.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/roji.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.rom-rom.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ror.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/rwc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/seed.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sense.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sense.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sprtshubcoin.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/solit.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/SNAX.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sov.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/placeholder.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/txt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/telos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/took.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/tpt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/tpt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/tro_256.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/trybe.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/usdb.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/usdetotokens-usde.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/USDT.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/USDT.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/USDT.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/usn.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/whaleex.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/wecash.jpg
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/wizz.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/worbli.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/gl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/gamblr.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/worktokenbviWRK.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/billionaire.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/zks.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/qbe.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/powx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/goldenchip.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pink_144.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pink-old_144.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/wax.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/OTCeoslogo1.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/EOSSTEEMpFULLres-527x504.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/weedcashnew1SteemEOSlogos1png.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/SANDtelosPNG1.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sqrl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/TLOSPonEOS.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/EOSPonTelos2.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eidos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/yas.png
wget https://raw.githubusercontent.com/yensesa/assets/master/sesacash-sm.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/legend.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/PEOPLE_Token_256.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xpr.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xbtc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xeth.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xusdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xmt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/usdc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/tusd.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xpax.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xpaxg.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/foobar.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xmda.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xdoge.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/MARF.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/NFD.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/GGWP.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/EOSBTCPzaxan.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/kanda2020new2.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/DDATEratzenPNG1.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken-boxgl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken-boxl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken-boxfc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dop.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/7chain_logo_black.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/TelosGolosPurple.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/kanda2020new2.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-btc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-eth.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-usdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-rrb.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-mnt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-ethfi.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-df.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-vinx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-comp.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-tmh.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/TCN-Tatch-transp.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/cron_token_logo.png
wget https://raw.githubusercontent.com/lichang-lab/eos-airdrops/master/logos/LC.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/btcup.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/btcdown.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosusdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/NICEONE.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bbt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/QUAD.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/VOID.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/yup.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-RED-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-ORANGE-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-YELLOW-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-GREEN-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-BLUE-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-INDIGO-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-VIOLET-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dad-logo.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/DECO.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ecoin.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/aether.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/mana.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/USDCASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/RUBCASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/UAHCASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/LIRUMOW.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/LIUAIEV.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ezar.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/koine.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/beatitude.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/cnt.png
wget https://vapaee.io/assets/logos/viitasphere.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/acorn.png


wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/teach.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pbtc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pbtc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/local-scale-logo.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/proxibots.png
wget https://raw.githubusercontent.com/eosasia/eos-dapps/master/telos/logos/telosdac.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/anudit-test.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/cts.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/word.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/word.png

wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/word.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/YKC.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/nut_225x225.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/city-seal-Blue-and-Gold-small-300x300.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pow.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/powx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/goldenchip.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pink_144.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pink-old_144.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/wax.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/OTCeoslogo1.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/EOSSTEEMpFULLres-527x504.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/weedcashnew1SteemEOSlogos1png.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/SANDtelosPNG1.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/sqrl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/TLOSPonEOS.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/EOSPonTelos2.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eidos.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/yas.png
wget https://raw.githubusercontent.com/yensesa/assets/master/sesacash-sm.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/legend.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/PEOPLE_Token_256.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xpr.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xbtc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xeth.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xusdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xmt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/usdc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/tusd.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xpax.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xpaxg.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/foobar.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xmda.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/xdoge.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/MARF.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/NFD.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/GGWP.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/EOSBTCPzaxan.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/kanda2020new2.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/DDATEratzenPNG1.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken-boxgl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken-boxl.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/lptoken-boxfc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dop.png

wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/7chain_logo_black.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/TelosGolosPurple.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/kanda2020new2.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-btc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-eth.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-usdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-rrb.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-mnt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-ethfi.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-df.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-vinx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-comp.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/issue.newdex-tmh.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/TCN-Tatch-transp.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/cron_token_logo.png
wget https://raw.githubusercontent.com/lichang-lab/eos-airdrops/master/logos/LC.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/btcup.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/btcdown.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/eosusdt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/NICEONE.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/bbt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/QUAD.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/VOID.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/yup.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-RED-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-ORANGE-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-YELLOW-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-GREEN-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-BLUE-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-INDIGO-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/visionfintec-VIOLET-100.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/dad-logo.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/peth.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pltc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pmkr.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pyfi.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/plink.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pnt.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pbal.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pband.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pcomp.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/psnx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/puni.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pant.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pbat.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pdai.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/plrc.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pomg.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/prep.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/pzrx.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/cat.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/fish.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/rat.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/DECO.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ecoin.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/aether.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/mana.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/USDCASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/RUBCASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/UAHCASH.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/LIRUMOW.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/LIUAIEV.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/ezar.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/koine.png
wget https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/beatitude.png